DELETE FROM Employee
WHERE EmployeeId = 1;

DELETE FROM Employee;

DROP TABLE ProductType;

CREATE TABLE Customer (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	DateCreated DATETIME NOT NULL, 
	Active BOOLEAN NOT NULL,
);

CREATE TABLE Product (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Price DOUBLE NOT NULL,
	Title TEXT NOT NULL,
	Description TEXT NOT NULL,
	Quantity INTEGER NOT NULL,
	DateCreated DATETIME NOT NULL,
	CustomerId INTEGER NOT NULL,
	ProductTypeId INTEGER NOT NULL,
		FOREIGN KEY(CustomerId) REFERENCES Customer(Id)
		FOREIGN KEY(ProductTypeId) REFERENCES ProductType(Id)
);

CREATE TABLE ProductType (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Type TEXT NOT NULL
);

CREATE TABLE PaymentType (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Type TEXT NOT NULL,
	AccountNumber INTEGER NOT NULL,
	DateCreated DATETIME NOT NULL,
	CustomerId INTEGER NOT NULL,
		FOREIGN KEY(CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE ItemOrder (
	CustomerId INTEGER NOT NULL,
	PaymentTypeId INTEGER NOT NULL,
	DateCreated DATETIME NOT NULL,
		FOREIGN KEY(CustomerId) REFERENCES Customer(Id),
		FOREIGN KEY(PaymentTypeId) REFERENCES PaymentType(Id)
);

CREATE TABLE ProductOrder (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ProductId INTEGER NOT NULL,
	ItemOrderId INTEGER NOT NULL,
		FOREIGN KEY(ProductId) REFERENCES Product(Id),
		FOREIGN KEY(ItemOrderId) REFERENCES ItemOrder(Id)
);

CREATE TABLE Employee (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	Supervisor BOOLEAN NOT NULL,
	DepartmentId INTEGER NOT NULL,
		FOREIGN KEY(DepartmentId) REFERENCES Department(Id)
);

CREATE TABLE Department (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	DepartmentName TEXT NOT NULL,
	Budget DOUBLE NOT NULL
);

CREATE TABLE TRAINING (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TrainingName TEXT NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	Capacity INTEGER NOT NULL
);

CREATE TABLE EmployeeTraining (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	EmployeeId INTEGER NOT NULL,
	TrainingId INTEGER NOT NULL,
		FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
		FOREIGN KEY(TrainingId) REFERENCES Training(Id)
);

CREATE TABLE Computer (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PurchaseDate DATETIME NOT NULL,
	DecommissionDate DATETIME NOT NULL,
	Manufacturer TEXT NOT NULL,
	Model TEXT NOT NULL
);

CREATE TABLE EmployeeComputer (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	AssignedDate DATETIME NOT NULL,
	UnassignedDate DATETIME NOT NULL,
	EmployeeId INTEGER NOT NULL,
	ComputerId INTEGER NOT NULL,
		FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
		FOREIGN KEY(ComputerId) REFERENCES Customer(Id)
);

INSERT INTO Department (DepartmentName, Budget) VALUES ("Looney Tunes", 1000000);

INSERT INTO Employee (FirstName, LastName, Supervisor, DepartmentId) VALUES ("Donald", "Duck", 1, 1); 

